In [1]:
import numpy as np

## NUMPY ARRAY

In [6]:
benimListem=[20,30,40]
type(benimListem)


list

In [8]:
np.array(benimListem)

array([20, 30, 40])

In [12]:
type(np.array(benimListem))

numpy.ndarray

In [14]:
matrixListe=[ [10,20,30] , [20,30,40] , [30,40,50] ]

In [16]:
matrixListe[1]

[20, 30, 40]

In [20]:
matrixListe[1][0]

20

In [24]:
np.array(matrixListe)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

## ARANGE

In [32]:
list(range(0,10))
# burada normal python ı kullandık

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [34]:
np.arange(0,10)
#  buradaysa numpy kütühanesini kullanarak aralığında verdiğimiz değer aralığında liste oluştue

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.arange(0,10,2)
# üçüncü değerstep size ı verir

array([0, 2, 4, 6, 8])

## ZEROS

In [40]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [42]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [44]:
np.zeros((9,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

 ## ONES

In [47]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [49]:
np.ones((9,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## LINSPACE

In [52]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [54]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [61]:
np.linspace(0,100,101)

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
        33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
        44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
        55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
        66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
        77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
        88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,
        99., 100.])

## EYE

In [64]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [66]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## RANDOM

In [69]:
np.random.randn(8)

array([ 1.6870489 ,  0.01567802,  0.06597801,  0.11468312,  0.01859132,
        0.43598723,  0.26061217, -0.59258747])

In [71]:
np.random.rand(4,4)

array([[0.73620942, 0.16799224, 0.49978399, 0.28517999],
       [0.69824465, 0.68464744, 0.15087579, 0.6621443 ],
       [0.9017275 , 0.80407657, 0.30214258, 0.16131078],
       [0.07163902, 0.44903569, 0.66094329, 0.34878093]])

In [77]:
np.random.randint(1,10)
# ilk yazılan dahil
# son yazılan dahil değil

1

In [75]:
np.random.randint(1,10,5)
#  sonuncu kaç tane random int istediğimizi belirtiyor

array([2, 8, 5, 3, 1])

In [79]:
benimNumpyDizim = np.arange(30)
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [88]:
benimRandomDizim = np.random.randint(0,100,20)

In [90]:
benimRandomDizim

array([98, 73, 24, 43, 97, 88, 86, 81, 91, 50, 25, 73, 30, 97, 35, 71, 54,
       87, 50, 67])

In [146]:
benimRandomDegerim = np.random.choice(benimRandomDizim)

In [148]:
benimRandomDegerim

73

## NUMPY DİZİ METHODLARI

In [96]:
benimNumpyDizim.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [98]:
benimNumpyDizim.reshape(10,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [106]:
benimNumpyDizim.max()

29

In [108]:
benimRandomDizim.max()

98

In [110]:
benimRandomDizim.min()

24

In [114]:
benimRandomDizim.argmax() 

0

In [118]:
benimRandomDizim.argmin()

2

In [124]:
benimNumpyDizim.shape

(30,)

Önceden reshape yaptığım dizi sadece o satırda değişti.  
Yani asıl dizimi değiştirmedi. 
Bunu unutma

In [129]:
reshapeDizim = benimNumpyDizim.reshape(5,6)

In [131]:
reshapeDizim

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [133]:
reshapeDizim.shape

(5, 6)