In [1]:
import numpy as np

In [3]:
benimDizim = np.arange(0,15)

In [5]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
benimDizim[5]

5

In [13]:
benimDizim[3:5]

array([3, 4])

In [15]:
benimDizim[2:6]

array([2, 3, 4, 5])

In [17]:
benimDizim[3:8] = -5

In [19]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [21]:
baskaDizi = np.arange(0,24)
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [23]:
slicingDizi = baskaDizi[4:9]
slicingDizi

array([4, 5, 6, 7, 8])

In [27]:
type(slicingDizi) 

numpy.ndarray

In [29]:
slicingDizi[:]=700

In [33]:
slicingDizi

array([700, 700, 700, 700, 700])

In [35]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

 Bir dizi içerisinnden bir parça lıp değiştirilirse asıl olan dizide değişir

In [38]:
ornekDizi = np.arange(0,24)

In [40]:
ornekDiziKopyasi = ornekDizi.copy()

In [44]:
ornekDiziKopyasi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [46]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [48]:
ornekDiziKopyasiSlicing= ornekDiziKopyasi[3:6]

In [50]:
ornekDiziKopyasiSlicing[:]=800

In [52]:
ornekDiziKopyasiSlicing

array([800, 800, 800])

In [56]:
ornekDiziKopyasi

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [58]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## MATRIX

In [61]:
benimListem= [[10,20,30],[20,30,40], [30,40,50]]

In [63]:
benimMatrixDizim = np.array(benimListem)

In [65]:
benimMatrixDizim

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

In [67]:
benimMatrixDizim[0]

array([10, 20, 30])

In [69]:
benimMatrixDizim[2][1]

40

In [71]:
benimMatrixDizim[1,2]

40

In [73]:
benimMatrixDizim[1:]

array([[20, 30, 40],
       [30, 40, 50]])

In [75]:
benimMatrixDizim[1:2]

array([[20, 30, 40]])

In [77]:
benimMatrixDizim[2:,:1]

array([[30]])

In [79]:
benimMatrixDizim[0:2,:1]

array([[10],
       [20]])

In [81]:
yeniListe=np.arange(0,25)

In [83]:
yeniListe

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [85]:
matrixYeniListe = yeniListe.reshape(5,5)
matrixYeniListe

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [89]:
matrixYeniListe[0]

array([0, 1, 2, 3, 4])

In [91]:
matrixYeniListe[[0,2,4]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [138]:
matrixYeniListe[[0],[2]]

array([2])

In [148]:
matrixYeniListe[[0,2,4],[1]]

array([ 1, 11, 21])

## OPERASYONLAR

In [151]:
yeniBirDizi = np.arange(5,25)
yeniBirDizi

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [153]:
yeniBirDizi=np.random.randint(1,100,20)

In [155]:
yeniBirDizi

array([11, 16, 47, 31, 33, 72, 14,  4, 59, 76, 91, 19, 11, 66,  4, 44,  1,
        9, 47, 55])

In [157]:
yeniBirDizi>24

array([False, False,  True,  True,  True,  True, False, False,  True,
        True,  True, False, False,  True, False,  True, False, False,
        True,  True])

In [159]:
sonucDizisi= yeniBirDizi>24

In [161]:
sonucDizisi

array([False, False,  True,  True,  True,  True, False, False,  True,
        True,  True, False, False,  True, False,  True, False, False,
        True,  True])

In [163]:
yeniBirDizi

array([11, 16, 47, 31, 33, 72, 14,  4, 59, 76, 91, 19, 11, 66,  4, 44,  1,
        9, 47, 55])

In [165]:
sonucDizisi[yeniBirDizi]

IndexError: index 47 is out of bounds for axis 0 with size 20

In [169]:
yeniBirDizi[sonucDizisi]

array([47, 31, 33, 72, 59, 76, 91, 66, 44, 47, 55])

In [171]:
yeniBirDizi[yeniBirDizi>24]

array([47, 31, 33, 72, 59, 76, 91, 66, 44, 47, 55])

In [173]:
sonDizi= np.arange(0,24)
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [175]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [177]:
sonDizi * sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [183]:
sonDizi - sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [181]:
sonDizi / sonDizi 

C:\Users\hasan\AppData\Local\Temp\ipykernel_23432\3618260773.py:1: RuntimeWarning: invalid value encountered in divide
  sonDizi / sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [185]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [187]:
np.max(sonDizi)

23

In [189]:
np.min(sonDizi)

0